// tabvision-client/src/utils/exporters.ts
import { TabDocument, TabNote } from '../types/tab';

interface MeasureSlot {
  timestamp: number;
  notes: TabNote[];
}

const STRING_NAMES = ['e', 'B', 'G', 'D', 'A', 'E'];
const SLOT_TOLERANCE = 0.05;
const TARGET_LINE_WIDTH = 60;

function bucketNotesByTime(notes: TabNote[]): MeasureSlot[] {
  const sorted = [...notes].sort((a, b) => a.timestamp - b.timestamp);
  const slots: MeasureSlot[] = [];

  for (const note of sorted) {
    const last = slots[slots.length - 1];
    if (last && Math.abs(note.timestamp - last.timestamp) < SLOT_TOLERANCE) {
      last.notes.push(note);
    } else {
      slots.push({ timestamp: note.timestamp, notes: [note] });
    }
  }

  return slots;
}

function formatSlotCell(slot: MeasureSlot, stringIdx: number): string {
  const stringNum = stringIdx + 1;
  const noteOnString = slot.notes.find((n) => n.string === stringNum);
  if (!noteOnString) return '-';
  if (noteOnString.fret === 'X') return 'x';
  return noteOnString.fret.toString();
}

function buildLineGroups(slots: MeasureSlot[]): MeasureSlot[][] {
  if (slots.length === 0) return [];

  const groups: MeasureSlot[][] = [];
  let current: MeasureSlot[] = [];
  let currentWidth = 0;

  for (const slot of slots) {
    const maxCellWidth = Math.max(
      ...Array.from({ length: 6 }, (_, i) => formatSlotCell(slot, i).length)
    );
    const cellWidth = maxCellWidth + 1;

    if (currentWidth + cellWidth > TARGET_LINE_WIDTH && current.length > 0) {
      groups.push(current);
      current = [];
      currentWidth = 0;
    }

    current.push(slot);
    currentWidth += cellWidth;
  }

  if (current.length > 0) groups.push(current);
  return groups;
}

function renderLineGroup(group: MeasureSlot[]): string[] {
  const cellWidths = group.map((slot) =>
    Math.max(...Array.from({ length: 6 }, (_, i) => formatSlotCell(slot, i).length)) + 1
  );

  return STRING_NAMES.map((label, stringIdx) => {
    const cells = group.map((slot, i) => {
      const cell = formatSlotCell(slot, stringIdx);
      return cell.padEnd(cellWidths[i], '-');
    });
    return `${label}|-${cells.join('-')}|`;
  });
}

export function exportToText(doc: TabDocument, title?: string): string {
  const lines: string[] = [];
  const docTitle = title?.trim() || 'TabVision Transcription';

  lines.push(docTitle);
  lines.push('='.repeat(docTitle.length));
  lines.push('');
  lines.push(`Tuning: ${doc.tuning?.join(' ') || 'E A D G B E'}`);
  if (doc.capoFret > 0) {
    lines.push(`Capo: fret ${doc.capoFret}`);
  }
  lines.push(`Duration: ${formatDuration(doc.duration)}`);
  lines.push(`Notes: ${doc.notes.length}`);
  lines.push('');

  if (doc.notes.length === 0) {
    lines.push('(No notes detected)');
    return lines.join('\n');
  }

  const slots = bucketNotesByTime(doc.notes);
  const groups = buildLineGroups(slots);

  for (let i = 0; i < groups.length; i++) {
    const group = groups[i];
    const startTime = formatDuration(group[0].timestamp);
    lines.push(`[${startTime}]`);
    lines.push(...renderLineGroup(group));
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by TabVision');
  return lines.join('\n');
}

export function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

export function downloadTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function exportToPdf(doc: TabDocument, title?: string): void {
  const tabText = exportToText(doc, title);
  const docTitle = (title?.trim() || 'TabVision Transcription').replace(/[<>]/g, '');

  const win = window.open('', '_blank', 'width=900,height=1100');
  if (!win) return;

  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${escapeHtml(docTitle)}</title>
<style>
  @page { margin: 0.75in; }
  body {
    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
    font-size: 11px;
    line-height: 1.4;
    color: #000;
    margin: 0;
    padding: 16px;
  }
  pre {
    white-space: pre-wrap;
    word-wrap: break-word;
    margin: 0;
  }
  @media print {
    body { padding: 0; }
  }
</style>
</head>
<body>
<pre>${escapeHtml(tabText)}</pre>
<script>
  window.addEventListener('load', () => {
    setTimeout(() => window.print(), 100);
  });
</script>
</body>
</html>`;

  win.document.open();
  win.document.write(html);
  win.document.close();
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
